### ISSUE TITLE
Only one patch can be loaded with multiple DaPlaya's

### ISSUE THREAD

**Issue by androvisuals** [cables-gl/cables-daplaya#1]
Tested the file cables.gl---da-Playa-0.0.4.exe from draft on windows 10.

I used this [patch](https://cables.gl/p/5d3abf9d02bd633c87edbee3) with an mp3
The mp3 file is stored locally here on my pc
C:\Users\andro\AppData\Roaming\cables-daplaya\patches\5d3abf9d02bd633c87edbee3

![image](https://user-images.githubusercontent.com/19530188/62059527-c62dca80-b223-11e9-9d38-881652f8a0d8.png)

Works fine with the internet disconnected :)

When loading two different DaPlayas they both load the same patch if i have no internet.

After talking with Tom we thought it'd be good that if we do `get patch` that an ID of the patch and its resources gets added to a local storage file in the same directory as DaPlaya.

The user could get 10 patches and then later on pick one from a drop down menu with no internet.
If a user loads up DaPlaya and there are no local patches then the `get patch` prompt should automatically pop up.

We want people to be able to zip that one directory with everything in it and send it to someone.

**Comment by steam0r** [comment]
thanks for testing. some feedback:

> When loading two different DaPlayas they both load the same patch if i have no internet.

hm, yes, this would be solved by:

> ID of the patch and its resources gets added to a local storage file in the same directory as DaPlaya.

that would look like this, i think:

```
daplaya.exe
patches/<patchId>/...
```

would that be okay? that would at least work in subdirectories and on an usb stick. i think it's kind of ugly though...but as far as i understand electron that would be possible.

> The user could get 10 patches and then later on pick one from a drop down menu with no internet.

so this would mean you need the apikey and then patchid for initially importing and then basically have a filebrowser over that "patches/" directory above for every "subdirectory" that has daplaya.exe? would be possible...

> We want people to be able to zip that one directory with everything in it and send it to someone.

yeah, get it, that would also be possible with the above setup, let me try this.

**Comment by androvisuals** [comment]
Perfect.

**Comment by androvisuals** [comment]
So everything is working great now. Two DaPlayas can run side by side. They should just both have different directory's for assets and such if they're two different files.
This is up to the user.
Gonna close this as this issue is solved.
Closed.
