### ISSUE TITLE
DaPlaya use cases

### ISSUE THREAD

**Issue by androvisuals** [cables-gl/cables-daplaya#2]
Use cases and thoughts in general for DaPlaya:

DaPlaya should have a folder for each patch with separate assets.
2 Playas should be able to be open separate patches that don't share one folder for assets and settings etc.

Soundcard output. No clue right now.I'd have to test this with hardware.

**VJ**
**Thoughts**
Typically a VJ uses something like Resolume avenue. 
This means that they have one screen with all of the video clips,parameters and effects. The other window is then pulled onto the external monitor/Beamer to show the visuals.

With DaPlaya we have no UI which makes these kind of operations pretty difficult. It'd be impossible to load new video files or textures into a Playa patch.
This would make VJ'ing with DaPlaya very hard as there's no UI feedback. Everything has to be committed to memory.
Not an actual problem right now as this isn't what the playa is primarily designed for.

**Use case**
All patches should have been downloaded to a laptop or USB stick.
They should all be able to be opened without any API keys after downloading.

A user could use a matrox triplehead to go with a resolution of 2160 * 480.
This would split the screen into 720 x 480 on 3 beamers.
Cables can already do this because its just making a window full screen on another monitor.

It'd be amazing if they could somehow see a sidebar screen with all the parameters that they've exposed (see above) on a separate window. This would make it pretty much fully usable as Basic VJ software. This is purely so they have visual feedback with things like midi controllers changing scenes etc..
We need to make a way for a user to pick a different midi controller via the sidebar 
(eg. I send a patch to a vj with a different virtual midi port)

**Gallery**
**Thoughts**
Some artists may make a cables patch on a MAC but the gallery computer may be a PC.
This would then require the user to generate a API key for the gallery so they can download the patch themselves and get it running on the other OS.

**Use case**
1 - Artist sets up the machine. Then the API key and patch ID should be fine.
2 - Gallery gets remote cables patch which has already been unlocked via zip file. This works if all assets are found in the same folder as DaPlaya and they have the same OS and kind of system.

A lot of generative artists normally build a `timer` into a patch so that they can say after 2 weeks the patch just displays black. This could probably be implemented into a cables patch with something that checks the date. Far easier than building it into DaPlaya.

It shouldn't work with validation via the web as most of these computers are offline to stop scheduled updates and other such things happening during a showing.

There's no real other scenarios that I can come up with right now as most differences are with things with hardware.

**Comment by steam0r** [comment]
closed for testing, almost all of the stuff is in there (apart from seperate window for sidebar)
