### ISSUE TITLE
Access Restriction Error

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables-daplaya#3]
i'm getting this error message when using daplayer with a cables patch playing a video

![image](https://user-images.githubusercontent.com/1138673/171602578-72b601c1-3f1e-4fc4-83f9-7a9b3b73debc.png)

bug, missing setting or user error ?

**Comment by wirmachenbunt** [comment]
my bad 
https://cables.gl/docs/faq/embedding/electron_files/electron_localfileaccess

**Comment by steam0r** [comment]
this is default enabled in the new release
